# Generated by Django 4.0.1 on 2022-02-10 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandIcons',
            fields=[
                ('id_brand_icon', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=50)),
                ('brand_icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSavedLogins',
            fields=[
                ('id_user_logins', models.BigAutoField(primary_key=True, serialize=False)),
                ('sitename', models.CharField(max_length=50)),
                ('username', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=140)),
                ('is_fav', models.BooleanField(default=False)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brand_icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pypass.brandicons')),
            ],
        ),
    ]
