# Generated by Django 4.0.1 on 2022-03-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pypass', '0002_alter_usersavedlogins_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandicons',
            old_name='brand_icon',
            new_name='brand_icon_class',
        ),
        migrations.AddField(
            model_name='brandicons',
            name='brand_importance_order',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='brandicons',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
