# Generated by Django 4.0.1 on 2022-03-14 20:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pypass', '0004_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandIcons',
            new_name='BrandIcon',
        ),
        migrations.RenameModel(
            old_name='UserSavedLogins',
            new_name='UserSavedLogin',
        ),
    ]
